# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  push:
    branches: ["master"]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: "step 1"
      run: echo "step 1"
  
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: "step 2"
      run: echo "step2"
      
