# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  push:
    branches: ["master"]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - name: "step check unzip"
      run: unzip
    
  job1:
    runs-on: ubuntu-latest
    steps:

    - name: "step -- checkout repository"
      uses: actions/checkout@v1

    - name: "step -- setup java"
      uses: actions/setup-java@v1
      with: {java-version: 11}

    - name: "step -- run unit tests"
      run: ./gradlew test

    - name: "step -- download test artifacts"
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-artifact
        path: app/build/reports/tests/testDebugUnitTest/
  
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - name: "step 2"
      run: ls -al
      
